export const APIUrl = {
  LOGIN: "/login",
  LOGIN_EMAIL: "/login/by",
  REGISTER: "/register",
  REGISTER_EMAIL: "/register/by",
  USER_PROFILE: "/user/profile",
  ADD_USER: "/addUser",
  ADDED_USER: "/get/added/user",
  GER_USER_ID: "/fetch/AddUser",
  DELET_USER_ID: "/delete/user",
  UPDATE_USER_ID: "/update/user",
  RESET_PWD: "/forgot/password",
  COMMENT: "/comment",
  GET_COMMENT: "/fetch/comment",
  DELETE_COMMENT_ID: "/delete/comment",
  CONTACT_US: "/contact/with/us",
  PHONE_OTP: "/send-otp/by/phone",
  EMAIL_OTP: "/send-otp/by/email",
};
